### ISSUE TITLE
Bitcoincharts API error

### ISSUE THREAD

**Issue by zot24** [kangasbros/django-bitcoin#25]
I'm having problem getting data from this URL `http://bitcoincharts.com/t/weighted_prices.json` so I decided to have a look to Bitcoincharts web site and I realise that they have now a different URL to call their API `http://api.bitcoincharts.com/v1/weighted_prices.json`

Should we change the URL that we are using in the code right now?

Cheers.

**Comment by miohtama** [comment]
Yep, the URL is old.

**Comment by zot24** [comment]
I'll fixed and pull a request.
