### ISSUE TITLE
Amount is reduced after a failed transaction

### ISSUE THREAD

**Issue by wladston** [kangasbros/django-bitcoin#4]
If you enter an invalid transaction (for example, sending bitcoins from a Wallet object to an invalid address), funds will get reduced from the Wallet anyways, even though no transaction was made.

for example : 

wallet.send_to_address('invalid address', Decimal('0.1'))

will debit 0.1 BTC from the wallet, even though no bitcoin was sent.

**Comment by kangasbros** [comment]
Fixed, now the error is catched and transaction object removed if it fails.
